context:
  version: "1.3.9"

package:
  name: bun
  version: ${{ version }}

source:
  - url: https://github.com/oven-sh/bun/archive/refs/tags/bun-v${{ version }}.tar.gz
    sha256: 844ee01f43cea34238d29c4637296ce438d61fb48fe2e633d8d27ceb761071f2
    patches:
      - 0001-don-t-require-rust.patch
      - 0002-unvendor-dependencies.patch
      - 0003-set-required-BUN_GIT_SHA-variable.patch
      - 0004-disable-werror.patch
      - 0005-add-targets-to-register_command.patch
      - 0006-don-t-use-static-libgcc-libcxx.patch
      - 0007-disable-ld_new.patch
      - 0008-don-t-use-llvm-toolchain.patch
      - if: linux
        then:
          - 0009-Use-system-ICU.patch
  - if: build_platform == "osx-64"
    then:
      url: https://github.com/oven-sh/bun/releases/download/bun-v${{ version }}/bun-darwin-x64.zip
      sha256: 588f4a48740b9a0c366a00f878810ab3ab5e6734d29b7c3cbdd9484b74a007de
      target_directory: bun.native
  - if: build_platform == "osx-arm64"
    then:
      url: https://github.com/oven-sh/bun/releases/download/bun-v${{ version }}/bun-darwin-aarch64.zip
      sha256: cde6a4edf19cf64909158fa5a464a12026fd7f0d79a4a950c10cf0af04266d85
      target_directory: bun.native
  - if: build_platform == "linux-aarch64"
    then:
      url: https://github.com/oven-sh/bun/releases/download/bun-v${{ version }}/bun-linux-aarch64.zip
      sha256: a2c2862bcc1fd1c0b3a8dcdc8c7efb5e2acd871eb20ed2f17617884ede81c844
      target_directory: bun.native
  - if: build_platform == "linux-64"
    then:
      url: https://github.com/oven-sh/bun/releases/download/bun-v${{ version }}/bun-linux-x64-baseline.zip
      sha256: 104d4d037f4b35e10215c0507e1779691f39c57bd91ddeefe11cad781e3fc4b9
      target_directory: bun.native
  - if: build_platform == "win-64"
    then:
      url: https://github.com/oven-sh/bun/releases/download/bun-v${{ version }}/bun-windows-x64.zip
      sha256: f4c1cf3549f6af986dc6535c40b4785ff1a7e7805e59637ec450fc11adb0c874
      target_directory: bun.native
  # these libraries are statically linked because they are internal forks
  - url: https://raw.githubusercontent.com/google/boringssl/refs/heads/main/LICENSE
    sha256: 827c8d8fc207c2392794eef9e00fe246f9f61fdcc132556c275be3dd8c3cd97f
    file_name: boringssl-LICENSE
  - url: https://raw.githubusercontent.com/microsoft/mimalloc/refs/heads/main/LICENSE
    sha256: 82ade5d7d9b029044b5fbbc326207fc47c2d44ee4dd71e8a559c36d728217de9
    file_name: mimalloc-LICENSE
  - url: https://raw.githubusercontent.com/TinyCC/tinycc/refs/heads/mob/COPYING
    sha256: 512d2d21b6b3384ba64781abb0208a1b87740bc31e2df48e2b206ddb7e4d5779
    file_name: tinycc-LICENSE
  - url: https://raw.githubusercontent.com/simdutf/simdutf/refs/heads/master/LICENSE-MIT
    sha256: fc8dbc04e03ad4efc08a647ffe7f995b811a95bc04c0e85a56d5277c6593fa5f
    file_name: simdutf-LICENSE-MIT
  - url: https://raw.githubusercontent.com/simdutf/simdutf/refs/heads/master/LICENSE-APACHE
    sha256: 3d34610fc6b5e1b0bfe4e2f36171c2d62c28ef05cb8d704f5a0073be41a43b3d
    file_name: simdutf-LICENSE-APACHE

build:
  skip: win
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - sed
    - ninja
    - pkg-config
    - lld
  host:
    - brotli
    - c-ares
    - hdrhistogram-c
    - if: linux
      then:
        - icu
    - libarchive
    - libdeflate
    - libhwy
    - libsqlite
    - lol-html
    - ls-hpack
    - zlib
    - zstd

tests:
  - package_contents:
      bin:
        - bun
        - bunx
      files:
        - share/bash-completion/completions/bun
        - share/zsh/site-functions/_bun
        - share/fish/vendor_completions.d/bun.fish
      strict: true
  - script:
      - bun --version
      - bun --help
      - bunx --version
      # simple smoke test
      - bunx cowsay hello

about:
  homepage: https://bun.sh
  repository: https://github.com/oven-sh/bun
  license: MIT
  license_file:
    - LICENSE.md
    - tinycc-LICENSE
    - boringssl-LICENSE
    - mimalloc-LICENSE
    - picohttp-LICENSE-MIT
    - simdutf-LICENSE-MIT
    - simdutf-LICENSE-APACHE
    - packages/bun-usockets/LICENSE
    - packages/bun-uws/LICENSE
    - src/deps/uucode/LICENSE.md
    - src/deps/zig-clap/LICENSE
  summary: Bun is a fast all-in-one JavaScript runtime

extra:
  recipe-maintainers:
    - xhochy
    - pavelzw
    - I-Al-Istannen
