conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  osx_arm64: azure
test: native_and_emulated
conda_install_tool: pixi
